# Generated by Django 3.1.5 on 2021-01-21 12:22

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=quiz.models.question_image_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to=quiz.models.quiz_image_path),
        ),
    ]
