# Generated by Django 3.1.5 on 2021-01-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210121_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='has_multipe_answers',
            new_name='has_multiple_answers',
        ),
    ]
