# Generated by Django 3.1.5 on 2021-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
